### ISSUE TITLE
Struct field support

### ISSUE THREAD

**Issue by jeremyBanks** [dtolnay/remain#1]
Neat package! I saw Alex Crichton mention it in his RustLatam talk about procedural macros, right after looking at rust-lang/rustfmt#3422 and rust-lang/rust-clippy#3822 discussing options for making sure that struct fields are sorted. This had was wondering if you were considering adding support for also ensuring that struct fields remain sorted, or if you wanted to keep it only focused on enums.

Cheers

**Comment by dtolnay** [comment]
I would accept a PR to support struct fields!
