### ISSUE TITLE
Can't bind remain::sorted to a different name

### ISSUE THREAD

**Issue by ElliotSis** [dtolnay/remain#11]
Hey there,

I was trying out the proc-macro-workshop for [`#[sorted]`](https://github.com/dtolnay/proc-macro-workshop#attribute-macro-sorted), and while coding it I thought of the following edge case (thanks for the awesome intro to macros btw!):

```rust
use remain::sorted as blah;

#[remain::check]
fn main() {
    let x = Some(3);
    #[blah]
    match x {
        None => {}
        Some(_) => {}
    }
}

```

The above code won't compile, I get the following error:

```
error[E0658]: attributes on expressions are experimental
 --> src/main.rs:6:5
  |
6 |     #[blah]
  |     ^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/15701

error[E0658]: custom attributes cannot be applied to expressions
 --> src/main.rs:6:5
  |
6 |     #[blah]
  |     ^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54727

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
```

I think this is because the code [here](https://github.com/dtolnay/remain/blob/master/src/visit.rs#L57) relies on the value of the path being either "sorted" or "remain :: sorted".
I assume the same would be true about the "unsorted" attribute.
This seems to show that relying on the imported attribute having a specific name may not be a good idea when developing a proc macro, since the user can bind it with a different name.

Is there a way to work around this (not that it's important)? If not, this may need to be highlighted in the documentation as being a limitation?

**Comment by ElliotSis** [comment]
Hum actually this may just be a non-issue; when using:

```rust
use remain::sorted as blah;
```

We're actually just renaming the proc macro attribute that is applied on methods, not what users rely on.

This code is still valid, it just has an unused import:

```rust
use remain::sorted as blah;

#[remain::check]
fn main() {
    let x = Some(3);
    #[sorted]
    match x {
        None => {}
        Some(_) => {}
    }
}
```

On nightly, this code runs perfectly fine:

```rust
#![feature(proc_macro_hygiene, stmt_expr_attributes)]

use remain::sorted as blah;

fn main() {
    let x = Some(3);
    #[blah]
    match x {
        None => {}
        Some(_) => {}
    }
}
```

Sorry for the confusion, feel free to close the issue!

**Comment by dtolnay** [comment]
Yeah I think this is fine as is.
